### ISSUE TITLE
Artifacts in rendering of mp3

### ISSUE THREAD

**Issue by adius** [andrewrk/waveform#11]
Rendering this mp3:
    https://github.com/adius/feetbeatz/blob/dev/mtqplayer/songs/highwaytohel.mp3

creates this png:
    https://github.com/adius/feetbeatz/blob/dev/mtqplayer/songs/highwaytohel.png

Unfortunately, there are artifacts at the right end of the image. Any idea how to fix this?

**Comment by andrewrk** [comment]
So here is what was happening:

The duration reported in the mp3 header was slightly longer than the audio data that was actually there. Due to a bug in the codebase, the waveform rendered trash in this part. I fixed that bug in the above commit.

Unfortunately it still means that the waveform png was generated with an incorrect length assumption, which means that instead of trash at the end, you get empty background. So to address that I will add a `--scan` flag which will scan the file to determine the exact correct duration, but then it will take twice as long to generate the final output.

**Comment by adius** [comment]
Wow, you're really fast at bugfixing :stuck_out_tongue: Thanks for that!
Isn't there another tool I can use to correct/normalize the songs?

**Comment by andrewrk** [comment]
Hmm good question. I don't know one off the top of my head. It's pretty normal for the duration metadata to be a bit off. I think a good music player app should be able to update the duration field if it knows the correct value and detects wrong metadata. In fact I think I'll add that as a [feature](https://github.com/andrewrk/groovebasin/issues/30) to Groove Basin :)
